[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_starter = "A7HBry8TeHZqgQ8cMeZwVTsE336gwSMGgV75MU6MMb5r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
